name: Auto Increment Version

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch  # Set to major, minor, or patch as per your preference
          WITH_V: true  # This prefixes the tag with 'v', e.g., v1.0.1