name: Auto Increment Version

on:
  push:
    branches:
      - main  # or your default branch, e.g., master

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history so tags are available for analysis

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch  # Set to major, minor, or patch as per your preference
          WITH_V: true  # This prefixes the tag with 'v', e.g., v1.0.1
